name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Install googletests
        run: ls
      - run: sudo apt-get install libgtest-dev
      - run: cd /usr/src/gtest
      - run: sudo cmake CMakeLists.txt
      - run: sudo make
      - run: sudo cp *.a /usr/lib
      - run: sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
      - run: sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
      - name: Compile and run tests
        run: g++ ./MultiMap/test.cpp -o ./MultiMap/test -lgtest -lpthread
      - run: ./MultiMap/test
      - name: Compile main
        run: g++ ./MultiMap/main.cpp -o ./MultiMap/main
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
            name: build
            path: |
              ./MultiMap/main
              ./MultiMap/test